import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-channel-distributor-special-pricing-recovery",
  "engine": "recovery",
  "title": "Channel Distributor Special-Pricing Recovery",
  "shortTitle": "Channel Distributor Special-Pricing Recovery",
  "tagline": "Validate channel special pricing and recover eligible credits while preventing duplicate or unauthorized claims.",
  "industry": "Channel Revenue Operations",
  "buyer": "Manufacturers and channel distributors",
  "uiPort": 4703,
  "apiPort": 5703,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Channel Distributor Special-Pricing Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions in one accountable workflow. Validate channel special pricing and recover eligible credits while preventing duplicate or unauthorized claims.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Channel Distributor Special-Pricing Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("program-authorization-library","CDS01","Program authorization library","Execute program authorization library using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed program authorization library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Program authorization library Reference","text","CDS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("end-customer-registry","CDS02","End-customer registry","Execute end-customer registry using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed end-customer registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","End-customer registry Reference","text","CDS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("product-eligibility-mapping","CDS03","Product eligibility mapping","Execute product eligibility mapping using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed product eligibility mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Product eligibility mapping Reference","text","CDS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("distributor-sales-ingestion","CDS04","Distributor sales ingestion","Execute distributor sales ingestion using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed distributor sales ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Distributor sales ingestion Reference","text","CDS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("contract-price-calculation","CDS05","Contract price calculation","Execute contract price calculation using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed contract price calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Contract price calculation Reference","text","CDS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("resale-price-validation","CDS06","Resale price validation","Execute resale price validation using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed resale price validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Resale price validation Reference","text","CDS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("claim-quantity-validation","CDS07","Claim quantity validation","Execute claim quantity validation using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed claim quantity validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Claim quantity validation Reference","text","CDS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("duplicate-claim-detection","CDS08","Duplicate claim detection","Execute duplicate claim detection using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed duplicate claim detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Duplicate claim detection Reference","text","CDS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("authorization-period-control","CDS09","Authorization period control","Execute authorization period control using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed authorization period control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Authorization period control Reference","text","CDS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("ship-and-debit-calculation","CDS10","Ship-and-debit calculation","Execute ship-and-debit calculation using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed ship-and-debit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Ship-and-debit calculation Reference","text","CDS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("manufacturer-claim-file","CDS11","Manufacturer claim file","Execute manufacturer claim file using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed manufacturer claim file decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Manufacturer claim file Reference","text","CDS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("rejection-remediation","CDS12","Rejection remediation","Execute rejection remediation using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed rejection remediation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Rejection remediation Reference","text","CDS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("credit-memo-matching","CDS13","Credit memo matching","Execute credit memo matching using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed credit memo matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Credit memo matching Reference","text","CDS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("distributor-settlement","CDS14","Distributor settlement","Execute distributor settlement using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed distributor settlement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Distributor settlement Reference","text","CDS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]}),
feature("program-customer-analytics","CDS15","Program customer analytics","Execute program customer analytics using special-price authorizations, end customers, products, distributor sales, ship-and-debit claims, eligibility, contract prices, credits, and deductions.","Produce a governed program customer analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Special Price Agreement","text","Distributor / Special Price Agreement · Standard Case"],["caseReference","Program customer analytics Reference","text","CDS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1332500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1612325],["domainDriver","Program Type","select","Ship and debit",["Ship and debit","Special bid","End-customer rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authorization library case","End-customer registry case","Product eligibility mapping case","Distributor sales ingestion case","Contract price calculation case"]})
]);
